# Generated by Django 4.1.7 on 2023-02-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
