# Generated by Django 4.1.7 on 2023-03-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='made',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
