# Generated by Django 4.1.7 on 2023-03-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_movieid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('movieid', models.CharField(max_length=265, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=1500)),
                ('year', models.CharField(max_length=4)),
                ('lent', models.CharField(max_length=10)),
                ('rate', models.IntegerField(default=0)),
                ('made', models.CharField(max_length=10, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('views_count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='watchl1',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='movie',
            name='watchl2',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='movie',
            name='watchl3',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='movie',
            name='watchl4',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
