# Generated by Django 4.1.7 on 2023-03-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_serie_movie_watchl1_movie_watchl2_movie_watchl3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='', upload_to='movies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('TR', 'TOP RATED'), ('MW', 'MOST WATCHED')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
