# Generated by Django 4.1.7 on 2023-03-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_poster_movie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('TR', 'TOP RATED'), ('MW', 'MOST WATCHED'), ('N', 'NEW')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movie',
            name='watchl1',
            field=models.CharField(default='', max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='watchl2',
            field=models.CharField(default='', max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='watchl3',
            field=models.CharField(default='', max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='watchl4',
            field=models.CharField(default='', max_length=1500, null=True),
        ),
    ]
