# Generated by Django 4.1.7 on 2023-03-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movie_status_alter_movie_watchl1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
