# Generated by Django 4.1.7 on 2023-03-09 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_movie_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500)),
                ('numbera', models.IntegerField(default=1)),
                ('rate', models.IntegerField(default=0)),
                ('watchl1', models.CharField(default='', max_length=1500, null=True)),
                ('watchl2', models.CharField(default='', max_length=1500, null=True)),
                ('watchl3', models.CharField(default='', max_length=1500, null=True)),
                ('watchl4', models.CharField(default='', max_length=1500, null=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serie_espo', to='movies.serie')),
            ],
        ),
    ]
