# Generated by Django 4.1.7 on 2023-03-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_espo'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='poster',
            field=models.ImageField(default='', upload_to='series'),
            preserve_default=False,
        ),
    ]
