# Generated by Django 4.1.7 on 2023-03-11 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_serie_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.movie')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.serie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='series',
            field=models.ManyToManyField(through='movies.Aio', to='movies.serie'),
        ),
    ]
