# Generated by Django 4.1.7 on 2023-03-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_aio_movie_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='espo',
            name='season',
            field=models.IntegerField(default=1),
        ),
    ]
