# Generated by Django 4.1.7 on 2023-03-13 00:09

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_espo_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='espo',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='serie',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='serie',
            name='status',
            field=models.CharField(choices=[('TR', 'TOP RATED'), ('MW', 'MOST WATCHED'), ('N', 'NEW')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='made',
            field=models.CharField(choices=[('AR', 'arabic'), ('EN', 'english')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serie',
            name='made',
            field=models.CharField(choices=[('AR', 'arabic'), ('EN', 'english')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
