# Generated by Django 4.1.7 on 2023-03-13 00:39

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_espo_created_movie_country_serie_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'دراما'), (2, 'اكشن'), (3, 'كوميدي'), (4, 'رومانسي'), (5, 'حربي'), (6, 'تشويق'), (7, 'رعب'), (8, 'خيال علمي'), (9, 'وثائقي'), (10, 'واقعي')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'دراما'), (2, 'اكشن'), (3, 'كوميدي'), (4, 'رومانسي'), (5, 'حربي'), (6, 'تشويق'), (7, 'رعب'), (8, 'خيال علمي'), (9, 'وثائقي'), (10, 'واقعي')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serie',
            name='status',
            field=models.CharField(blank=True, choices=[('TR', 'TOP RATED'), ('MW', 'MOST WATCHED'), ('N', 'NEW')], max_length=2),
        ),
    ]
