# Generated by Django 4.1.7 on 2023-03-13 00:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_movie_category_serie_category_alter_serie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('drama', 'دراما'), ('action', 'اكشن'), ('comedy', 'كوميدي'), ('romance', 'رومانسي'), ('war', 'حربي'), ('exciting', 'تشويق'), ('horror', 'رعب'), ('fantasia', 'خيال علمي'), ('deco', 'وثائقي'), ('real', 'واقعي')], max_length=100),
        ),
        migrations.AlterField(
            model_name='serie',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('drama', 'دراما'), ('action', 'اكشن'), ('comedy', 'كوميدي'), ('romance', 'رومانسي'), ('war', 'حربي'), ('exciting', 'تشويق'), ('horror', 'رعب'), ('fantasia', 'خيال علمي'), ('deco', 'وثائقي'), ('real', 'واقعي')], max_length=100),
        ),
    ]
