# Generated by Django 4.1.7 on 2023-03-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_alter_movie_category_alter_serie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[(1, 'دراما'), (2, 'اكشن'), (3, 'كوميدي'), (4, 'رومانسي'), (5, 'حربي'), (6, 'تشويق'), (7, 'رعب'), (8, 'خيال علمي'), (9, 'وثائقي'), (10, 'واقعي')], max_length=100),
        ),
        migrations.AlterField(
            model_name='serie',
            name='category',
            field=models.CharField(choices=[(1, 'دراما'), (2, 'اكشن'), (3, 'كوميدي'), (4, 'رومانسي'), (5, 'حربي'), (6, 'تشويق'), (7, 'رعب'), (8, 'خيال علمي'), (9, 'وثائقي'), (10, 'واقعي')], max_length=100),
        ),
    ]
