# Generated by Django 4.1.7 on 2023-03-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_alter_movie_category_alter_serie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
