# Generated by Django 4.1.7 on 2023-03-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_movie_created_serie_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='label',
            field=models.CharField(choices=[(1, 'مسلسلات عربي'), (2, 'افلام عربي'), (3, 'مسلسلات اجنبي'), (4, 'افلام اجنبي'), (5, 'مسلسلات تركي'), (6, 'مسلسلات كوري'), (7, 'بوليوود')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='label',
            field=models.CharField(choices=[(1, 'مسلسلات عربي'), (2, 'افلام عربي'), (3, 'مسلسلات اجنبي'), (4, 'افلام اجنبي'), (5, 'مسلسلات تركي'), (6, 'مسلسلات كوري'), (7, 'بوليوود')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
