# Generated by Django 4.1.7 on 2023-03-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_movie_label_serie_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='label',
            field=models.CharField(choices=[('ARSER', 'مسلسلات عربي'), ('ARFILM', 'افلام عربي'), ('ENSER', 'مسلسلات اجنبي'), ('ENFILM', 'افلام اجنبي'), ('TURKSER', 'مسلسلات تركي'), ('KURSER', 'مسلسلات كوري'), ('BUL', 'بوليوود')], max_length=10),
        ),
        migrations.AlterField(
            model_name='serie',
            name='label',
            field=models.CharField(choices=[('ARSER', 'مسلسلات عربي'), ('ARFILM', 'افلام عربي'), ('ENSER', 'مسلسلات اجنبي'), ('ENFILM', 'افلام اجنبي'), ('TURKSER', 'مسلسلات تركي'), ('KURSER', 'مسلسلات كوري'), ('BUL', 'بوليوود')], max_length=10),
        ),
    ]
