# Generated by Django 4.1.7 on 2023-03-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_alter_movie_label_alter_serie_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('دراما', 'دراما'), ('اكشن', 'اكشن'), ('كوميدي', 'كوميدي'), ('رومانسي', 'رومانسي'), ('حربي', 'حربي'), ('تشويق', 'تشويق'), ('رعب', 'رعب'), ('خيال علمي', 'خيال علمي'), ('وثائقي', 'وثائقي'), ('واقعي', 'واقعي')], max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='label',
            field=models.CharField(choices=[('مسلسلات_عربي', 'مسلسلات عربي'), ('افلام_عربي', 'افلام عربي'), ('مسلسلات_عربي', 'مسلسلات اجنبي'), ('افلام_اجنبي', 'افلام اجنبي'), ('مسلسلات_تركي', 'مسلسلات تركي'), ('مسلسلات_كوري', 'مسلسلات كوري'), ('بوليوود', 'بوليوود')], max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('TOP RATED', 'TOP RATED'), ('MOST WATCHED', 'MOST WATCHED'), ('NEW', 'NEW')], max_length=100),
        ),
        migrations.AlterField(
            model_name='serie',
            name='category',
            field=models.CharField(choices=[('دراما', 'دراما'), ('اكشن', 'اكشن'), ('كوميدي', 'كوميدي'), ('رومانسي', 'رومانسي'), ('حربي', 'حربي'), ('تشويق', 'تشويق'), ('رعب', 'رعب'), ('خيال علمي', 'خيال علمي'), ('وثائقي', 'وثائقي'), ('واقعي', 'واقعي')], max_length=100),
        ),
        migrations.AlterField(
            model_name='serie',
            name='label',
            field=models.CharField(choices=[('مسلسلات_عربي', 'مسلسلات عربي'), ('افلام_عربي', 'افلام عربي'), ('مسلسلات_عربي', 'مسلسلات اجنبي'), ('افلام_اجنبي', 'افلام اجنبي'), ('مسلسلات_تركي', 'مسلسلات تركي'), ('مسلسلات_كوري', 'مسلسلات كوري'), ('بوليوود', 'بوليوود')], max_length=100),
        ),
        migrations.AlterField(
            model_name='serie',
            name='status',
            field=models.CharField(blank=True, choices=[('TOP RATED', 'TOP RATED'), ('MOST WATCHED', 'MOST WATCHED'), ('NEW', 'NEW')], max_length=100),
        ),
    ]
